---
- hosts: localhost
  tasks:
  - name: Collect information for Pure Storage
    purestorage.fusion.fusion_info:
      gather_subset: all
      app_id: "{{ ansible_env.API_CLIENT }}"
      key_file: "{{ ansible_env.PRIV_KEY_FILE }}"

    register: fusion_info

  - name: Show Resources
    ansible.builtin.debug:
      msg:
        - "Storage Services:"
        - "{{ fusion_info['fusion_info']['storage_services'] }}"
        - "Storage Class:"
        - "{{ fusion_info['fusion_info']['storageclass'] }}"
        - "Protection Policies:"
        - "{{ fusion_info['fusion_info']['protection_policies'] }}"
