---
- hosts: localhost

  tasks:
    - ansible.builtin.include_vars: group_vars/consumer.yml
    - ansible.builtin.set_fact:
        tenants_dict: { }

    - name: Check private key exists
      ansible.builtin.stat:
        path: "{{ ansible_env.PRIV_KEY_FILE }}"
      register: result

    - name: End run if missing private key
      ansible.builtin.meta: end_play
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)

    - name: "Creates work directory {{ workdir }}"
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: directory

    - name: "Creates tenants folders"
      ansible.builtin.file:
        path: "{{ workdir }}/{{ item.name }}"
        state: directory
      loop: "{{ tenants }}"

    - name: Create new tenant(s)
      purestorage.fusion.fusion_tenant:
        app_id: "{{ ansible_env.API_CLIENT }}"
        key_file: "{{ ansible_env.PRIV_KEY_FILE }}"
        state: present # or absent
        name: "{{ item.name }}"
        display_name: "{{ item.display_name }}"
      loop: "{{ tenants }}"

    - name: Create a Private RSA key
      community.crypto.openssl_privatekey:
        path: "{{ workdir }}/{{ item.name }}/priv_{{ item.name }}.pem"
        type: RSA
        size: "{{ key_size }}"
      loop: "{{ tenants }}"

    - name: Create a Public RSA key
      community.crypto.openssl_publickey:
        path: "{{ workdir }}/{{ item.name }}/pub_{{ item.name }}.pem"
        privatekey_path: "{{ workdir }}/{{ item.name }}/priv_{{ item.name }}.pem"
      loop: "{{ tenants }}"

    - name: Create new API client foo
      purestorage.fusion.fusion_api_client:
        app_id: "{{ ansible_env.API_CLIENT }}"
        key_file: "{{ ansible_env.PRIV_KEY_FILE }}"
        state: present
        name: "{{ item.name }}"
        public_key: "{{ lookup('file', workdir + '/' + item.name + '/pub_' + item.name + '.pem') }}"
      loop: "{{ tenants }}"

    - name: Convert Tenant list to dict
      ansible.builtin.set_fact:
        tenants_dict: "{{ tenants_dict | combine({item.name: item.display_name}) }}"
      with_items:
        - "{{ tenants }}"

    - name: Collect Api Clients
      purestorage.fusion.fusion_info:
        gather_subset: api_clients
        app_id: "{{ ansible_env.API_CLIENT }}"
        key_file: "{{ ansible_env.PRIV_KEY_FILE }}"
      register: fusion_info

    - name: Creating a file .iss in tenant folder
      ansible.builtin.copy:
        dest: "{{ workdir }}/{{ item.value.display_name }}/{{ item.value.display_name }}.iss"
        content: "{{ item.value.issuer }}"
      with_dict: "{{ fusion_info['fusion_info']['api_clients'] }}"
      when: item.value.display_name in tenants_dict.keys()

    - name: Role Assignment to Tenant(s)
      purestorage.fusion.fusion_ra:
        app_id: "{{ ansible_env.API_CLIENT }}"
        key_file: "{{ ansible_env.PRIV_KEY_FILE }}"
        state: present
        name: "tenant-admin"
        scope: "tenant"  # "organization" "tenant_space"
        tenant: "{{ item.value.display_name }}"
        user: "{{ item.value.issuer }}"
      with_dict: "{{ fusion_info['fusion_info']['api_clients'] }}"
      when: item.value.display_name in tenants_dict.keys()
