---
- hosts: Initiators_Hosts

  become: true
  tasks:

    - name: Obtain IQN from Initiators_Hosts
      ansible.builtin.shell: cat /etc/iscsi/initiatorname.iscsi | grep "^InitiatorName=iqn" | awk -F'=' '{print $2}'
      register: iqn

    - name: IQN Results
      ansible.builtin.debug:
        msg:
          - "Inventory Hostname: {{ inventory_hostname }}"
          - "Hostname: {{ ansible_hostname }}"
          - "IQN: {{ iqn.stdout }}"

- hosts: localhost

  tasks:
    - ansible.builtin.include_vars: group_vars/workloads.yml

    - ansible.builtin.set_fact:
        iqn_data: []
        map_volumes: { }

    - name: Check private key exists
      ansible.builtin.stat:
        path: "{{ priv_key_file }}"
      register: result

    - name: End run if missing private key
      ansible.builtin.meta: end_play
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)

    - name: Create IQN/Hostname dictionary
      ansible.builtin.set_fact:
        iqn_data: "{{ iqn_data|default({}) + [ {'hostname':item, 'iqn':(hostvars[item]['iqn'].stdout)} ] }}"
      with_items:
        - "{{ groups['Initiators_Hosts'] }}"

    - name: Create host access policy
      purestorage.fusion.fusion_hap:
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
        state: "present"
        name: "{{ item.hostname }}"
        display_name: "{{ item.hostname }}"
        personality: "linux"
        iqn: "{{ item.iqn }}"
      with_items: "{{ iqn_data }}"
      when: item.iqn != ""

    - name: Create new tenant space(s)
      purestorage.fusion.fusion_ts:
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
        state: "present" # or absent
        name: "{{ item.name }}"
        display_name: "{{ item.display_name }}"
        tenant: "{{ item.tenant }}"
      loop: "{{ tenant_space }}"

    - name: Create new placement group(s)
      purestorage.fusion.fusion_pg:
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
        state: "present" # or absent
        name: "{{ item.name }}"
        display_name: "{{ item.display_name }}"
        tenant: "{{ item.tenant }}"
        tenant_space: "{{ item.tenant_space }}"
        availability_zone: "{{ item.availability_zone }}"
        storage_service: "{{ item.storage_service }}"
        region: "{{ item.region }}"
      loop: "{{ placement_groups }}"

    - name: Create new volume(s)
      purestorage.fusion.fusion_volume:
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
        state: "present" # or absent
        name: "{{ item.name }}"
        display_name: "{{ item.display_name }}"
        size: "{{ item.size }}"
        storage_class: "{{ item.storage_class }}"
        tenant: "{{ item.tenant }}"
        tenant_space: "{{ item.tenant_space }}"
        placement_group: "{{ item.placement_group }}"
        host_access_policies: "{{ item.host_access_policies }}"
      loop: "{{ volumes }}"

    - name: Get Volumes info
      purestorage.fusion.fusion_info:
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
        gather_subset: volumes
      register: fusion_info

    - name: Map Volumes with (Serial ID and IQN )
      ansible.builtin.set_fact:
        map_volumes: >-
          {{ map_volumes|combine(
          { item.value.name.lower() : { 'serial':(prefix_disk + item.value.serial_number).lower(), 'iqn':(item.value.target.iscsi.iqn).lower()} }
          ) }}
      with_dict: "{{ fusion_info['fusion_info']['volumes'] }}"

    - name: Get Purestorage Storage Endpoints
      purestorage.fusion.fusion_info:
        gather_subset: storage_endpoints
        app_id: "{{ api_client }}"
        key_file: "{{ priv_key_file }}"
      register: reg_fusion_info

- hosts: Initiators_Hosts
  become: true
  tasks:
    - ansible.builtin.set_fact:
        valid_volumes: { }
        devices: { }
        iscsi_interfaces: []
        list_ip: []
        iqn_list: []
        reg_fusion_info: "{{ hostvars['localhost']['reg_fusion_info'] }}"

    - name: Obtain list of volumes to mount
      ansible.builtin.set_fact:
        valid_volumes: "{{ valid_volumes|combine( {item.name: item.mount_path} ) }}"
      with_items: "{{ hostvars['localhost']['volumes'] }}"
      when: inventory_hostname in item.host_access_policies

    - ansible.builtin.debug: msg="{{ valid_volumes }}"

    - name: Parse volume, mount path and volume id
      ansible.builtin.set_fact:
        devices: "{{ devices|combine( { valid_volumes[item.key]:item.value } ) }}"
      with_dict: "{{ hostvars['localhost']['map_volumes'] }}"
      when: item.key in valid_volumes.keys()

    - ansible.builtin.debug:
        msg:
          - "Mount: /dev/mapper/{{ item.value.serial }}"
          - "On: {{ item.key }}"
      with_dict: "{{ devices }}"

    - name: Get a list of iscsi_interfaces
      ansible.builtin.set_fact:
        iscsi_interfaces: "{{ iscsi_interfaces + [reg_fusion_info['fusion_info']['storage_endpoints'][item]['iscsi_interfaces']] }}"
      with_items: "{{ reg_fusion_info['fusion_info']['storage_endpoints'].keys() }}"

    - name: Extract IP from iscsi_interfaces
      ansible.builtin.set_fact:
        list_ip: "{{ list_ip + [item['address'].split('/')[0]] }}"
      with_items: "{{ iscsi_interfaces }}"

    - name: "Perform a discovery and show available target nodes"
      community.general.open_iscsi:
        show_nodes: true
        discover: true
        ip: "{{ item }}"
      with_items: "{{ list_ip }}"

    - name: Get a list of IQN with unique elements
      ansible.builtin.set_fact:
        iqn_list: "{{ iqn_list + [ item.value.iqn ] }}"
      with_dict: "{{ devices }}"
      when: item.value.iqn not in iqn_list

    - name: Connect to the named target
      community.general.open_iscsi:
        login: true
        target: "{{ item }}"
      loop: "{{ iqn_list }}"

    - name: Create a primary partition
      community.general.parted:
        device: "/dev/mapper/{{ item.value.serial }}"
        number: 1
        state: present
      with_dict: "{{ devices }}"

    - name: Create/check ext4 partition
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/mapper/{{ item.value.serial }}-part1"
      with_dict: "{{ devices }}"

    - name: Creates directory for mountpoints
      ansible.builtin.file:
        path: "{{ item.key }}"
        state: directory
      with_dict: "{{ devices }}"

    - name: Mount volumes
      ansible.posix.mount:
        path: "{{ item.key }}"
        src: "/dev/mapper/{{ item.value.serial }}-part1"
        fstype: ext4
        state: mounted
      with_dict: "{{ devices }}"

    - name: Install fio
      ansible.builtin.package:
        name: fio
        state: present

    - name: Copy initiator_random_write.fio
      ansible.builtin.copy:
        src: "./files/initiator_random_write.fio"
        dest: "/tmp/initiator_random_write.fio"

    - name: Run FIO process
      ansible.builtin.command: "chdir={{ item.mount_path }} fio /tmp/initiator_random_write.fio"
      with_items: "{{ hostvars['localhost']['volumes'] }}"
      register: ps

    - name: FIO Results
      ansible.builtin.debug: var=ps.stdout_lines
