---
- hosts: localhost
  tasks:
  - name: Collect information for Pure Storage fleet in Pure1
    purestorage.fusion.fusion_info:
      gather_subset: all
      app_id: "{{ ansible_env.API_CLIENT}}"
      key_file: "{{ ansible_env.PRIV_KEY_FILE}}"
